#!/bin/bash
set -e

RELEASE=1.13.0
JAR_NAME="google-java-format-${RELEASE}-all-deps.jar"
RELEASES_URL=https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format
JAR_URL="${RELEASES_URL}/${RELEASE}/${JAR_NAME}"

CACHE_DIR="$HOME/.cache/google-java-format-git-pre-commit-hook"
JAR_FILE="$CACHE_DIR/$JAR_NAME"
JAR_DOWNLOAD_FILE="${JAR_FILE}.tmp"
JAR_PGP_ASC_FILE="${JAR_FILE}.asc"
PGP_SIGN_KEY_ID=E77417AC194160A3FABD04969A259C7EE636C5ED

if [[ ! -f "$JAR_FILE" ]]
then
    mkdir -p "$CACHE_DIR"
    curl -L "$JAR_URL" -o "$JAR_DOWNLOAD_FILE"

    # Downloaded from: "${JAR_URL}.asc"
    cat >"$JAR_PGP_ASC_FILE" <<EOF
-----BEGIN PGP SIGNATURE-----

iQIzBAABCgAdFiEE53QXrBlBYKP6vQSWmiWcfuY2xe0FAmBk8GgACgkQmiWcfuY2
xe15Ag/+PIPIhwPo5S0eVHsPuaH2F7gmjedJAlO/sP+XksHw3r9kvDHhxhtjzpaB
nVUsj4xSTU/8TcG/GDGCWZPI8eqA+2184Wf+IDzm36oIRCSJwvEBmqCyG/ffxUzl
K2sf8IoptGTWqfZTBu53jskGhVwuV0EqrnxBpaLvNbb019GI20YqcEeVC61f6fje
yGM7MO/bTKtwr3p0GDddmxKghkTr/GQxmRHXH1PY2nyJi51yZnefGA8rXkNGAQnQ
xahvxDWsqipdvokfYEC5LSnRXeB9oMHAsKrWwmlJXpvXS0z56pPqM8wO5OYnssTd
DEVR7w/t4ldXS5Y3SA3B5cdOfUb8CVqzRz9Ht8g3/Pc9JfgRKl3s+JGfj9np41pd
2zBzdY7a+5PjYi08WgVDcQYSuswAM7/71l2tKV88E9dqArPausYatRndvAfKivVF
kUgEFCARhqNFS/8TtC9DPjJc0a2toEyrHurt33jPknfWHM2yhaW2wSfeDagfSHE0
4pbusMBCesRk1lJZdcqNARqOtgfZD3V1J2CQ/3MCqTB0Z+Yzhxya5rLojfXQJNu1
IhVd5OjdmBxL4UHdVLYvlBd16ng91GfsO91aedTL7TOFB9QZm4U35yknFYUcqHlL
RkMpZx8/4hNMT8HicpUjBvF45yNpUL3bix71MJfl4ILG8dRE3ho=
=b349
-----END PGP SIGNATURE-----
EOF

    if ! gpg --list-keys "$PGP_SIGN_KEY_ID"
    then
        gpg --keyserver hkps://keyserver.ubuntu.com --recv-key "$PGP_SIGN_KEY_ID"
    fi
    gpg --verify "$JAR_PGP_ASC_FILE" "$JAR_DOWNLOAD_FILE"
    mv "$JAR_DOWNLOAD_FILE" "$JAR_FILE"
fi

changed_java_files=$(git diff --cached --name-only --diff-filter=ACMR | grep ".*java$" || true)
if [[ -n "$changed_java_files" ]]
then
    echo "Reformatting Java files: $changed_java_files"
    if ! java   --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
                --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
                -jar "$JAR_FILE" --replace --set-exit-if-changed $changed_java_files
    then
        echo "An error occured, aborting commit!" >&2
        exit 1
    fi
else
    echo "No Java files changes found."
fi
